<a href="https://colab.research.google.com/github/PoojithaYarava/Python-For-Data-Science-/blob/main/PFDS_Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Recursive Call Stack Visualization

In [10]:
def recursive_factorial(n):
  """Calculates the factorial of a non-negative integer using recursion."""
  if n == 0:
    return 1
  else:
    return n * recursive_factorial(n-1)

In [11]:
n = int(input("Enter the total number of people (n): "))
r = int(input("Enter the number of places (r): "))

Enter the total number of people (n): 5
Enter the number of places (r): 5


In [12]:
if n < r:
    print("Error: The number of people (n) must be greater than or equal to the number of places (r).")
else:
    # Step 1: Calculate n!
    print(f"Step 1: Calculate n! ({n}!)")
    n_factorial = recursive_factorial(n)
    print(f"{n}! = {n_factorial}")

    # Step 2: Calculate (n - r)!
    n_minus_r = n - r
    print(f"\nStep 2: Calculate (n - r)! ({n} - {r})! = {n_minus_r}!")
    n_minus_r_factorial = recursive_factorial(n_minus_r)
    print(f"{n_minus_r}! = {n_minus_r_factorial}")

    # Step 3: Calculate nPr
    print(f"\nStep 3: Calculate nPr using the formula nPr = n! / (n - r)!")
    npr_result = n_factorial // n_minus_r_factorial  # Use integer division
    print(f"{n}P{r} = {n_factorial} / {n_minus_r_factorial} = {npr_result}")

Step 1: Calculate n! (5!)
5! = 120

Step 2: Calculate (n - r)! (5 - 5)! = 0!
0! = 1

Step 3: Calculate nPr using the formula nPr = n! / (n - r)!
5P5 = 120 / 1 = 120


2.Compare Recursive vs Iterative Approaches

In [13]:
def fact(n, depth=0):
    space = "  " * depth
    if n == 0 or n == 1:
        return 1
    else:
        res = n * fact(n - 1, depth + 1)
        return res

num = int(input("Enter a number (≤ 10): "))
if 0 <= num <= 10:
    result = fact(num)
    print(f"\nResult: {result}")
else:
    print("Invalid input. Please enter a number between 0 and 10.")

Enter a number (≤ 10): 5

Result: 120


In [14]:

import numpy as np

marks = np.array([
    [85, 78, 92],
    [67, 88, 75],
    [90, 94, 89],
    [76, 64, 70],
    [82, 79, 85]
])

avg_per_student = np.mean(marks, axis=1)
min_per_student = np.min(marks, axis=1)
max_per_student = np.max(marks, axis=1)

print("Marks Array:\n", marks)
print("\nAverage Marks per Student:", avg_per_student)
print("Minimum Marks per Student:", min_per_student)
print("Maximum Marks per Student:", max_per_student)

print("\nMarks of 2nd and 4th student:\n", marks[[1, 3]])

high_scorers = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 in any subject:\n", marks[high_scorers])

reshaped = marks.T
print("\nReshaped Array (Subject-wise):\n", reshaped)

Marks Array:
 [[85 78 92]
 [67 88 75]
 [90 94 89]
 [76 64 70]
 [82 79 85]]

Average Marks per Student: [85.         76.66666667 91.         70.         82.        ]
Minimum Marks per Student: [78 67 89 64 79]
Maximum Marks per Student: [92 88 94 76 85]

Marks of 2nd and 4th student:
 [[67 88 75]
 [76 64 70]]

Students scoring above 80 in any subject:
 [[85 78 92]
 [67 88 75]
 [90 94 89]
 [82 79 85]]

Reshaped Array (Subject-wise):
 [[85 67 90 76 82]
 [78 88 94 64 79]
 [92 75 89 70 85]]


In [15]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [67, 88, 75],
    [90, 94, 89],
    [76, 64, 70],
    [82, 79, 85]
])

avg_per_student = np.mean(marks, axis=1)
min_per_student = np.min(marks, axis=1)
max_per_student = np.max(marks, axis=1)

print("Marks Array:\n", marks)
print("\nAverage Marks per Student:", avg_per_student)
print("Minimum Marks per Student:", min_per_student)
print("Maximum Marks per Student:", max_per_student)

print("\nMarks of 2nd and 4th student:\n", marks[[1, 3]])

high_scorers = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 in any subject:\n", marks[high_scorers])

reshaped = marks.T
print("\nReshaped Array (Subject-wise):\n", reshaped)


Marks Array:
 [[85 78 92]
 [67 88 75]
 [90 94 89]
 [76 64 70]
 [82 79 85]]

Average Marks per Student: [85.         76.66666667 91.         70.         82.        ]
Minimum Marks per Student: [78 67 89 64 79]
Maximum Marks per Student: [92 88 94 76 85]

Marks of 2nd and 4th student:
 [[67 88 75]
 [76 64 70]]

Students scoring above 80 in any subject:
 [[85 78 92]
 [67 88 75]
 [90 94 89]
 [82 79 85]]

Reshaped Array (Subject-wise):
 [[85 67 90 76 82]
 [78 88 94 64 79]
 [92 75 89 70 85]]
